version: '3'
services:
  apache:
    build:
      context: ./
      dockerfile: apache.Dockerfile
    container_name: 'apache'
    restart: 'always'
    ports:
      - ${APACHE_PORT}:80
      - ${APACHE_PORT_SSL}:443
    links:
      - mysql
    environment:
      - SITE_ROOT:${SITE_ROOT}
    volumes:
      - ${DOCUMENT_ROOT}:${SITE_ROOT}
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${LOG_DIR}/apache2:/var/log/apache2
      - ${SITES_AVAILABLE}:/etc/apache2/sites-available
      - ${SSL_DIR}:/etc/apache2/ssl
  mysql:
    build:
      context: ./mysql
    container_name: 'mysql'
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./${LOG_DIR}/mysql:/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql-slave:
    build:
      context: ./mysql-slave
    container_name: 'mysql-slave'
    restart: 'always'
    depends_on:
      - mysql
    ports:
      - '33060:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MASTER_USER: ${MASTER_USER}
      MASTER_PASSWORD: ${MASTER_PASSWORD}
      MASTER_HOST: ${MASTER_HOST}
    volumes:
      - ./mysql-slave/conf.d:/etc/mysql/conf.d
      - ./mysql-slave/scripts:/root/scripts
    links:
      - mysql